name: Post-Merge Security Review

on:
  issue_comment:
    types: [created]

jobs:
  security-review-comment:
    # Only run on PR comments
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install @actions/core @actions/github

      - name: Post security review approval
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Check if comment contains trigger phrase (case-insensitive)
            const commentBody = context.payload.comment.body.toLowerCase();
            const hasTriggerPhrase = commentBody.includes('security review passed') ||
                                     commentBody.includes('security review complete');

            if (!hasTriggerPhrase) {
              console.log('Comment does not contain security review trigger phrase. Skipping.');
              return;
            }

            // Load the security review script
            const scriptPath = path.join(process.env.GITHUB_WORKSPACE, '.github/scripts/security-review.js');
            const scriptContent = fs.readFileSync(scriptPath, 'utf8');

            // Set up inputs for the script
            process.env.INPUT_GITHUB_TOKEN = process.env.GITHUB_TOKEN;
            process.env.INPUT_PR_NUMBER = context.issue.number;
            process.env.INPUT_REVIEWER = context.payload.comment.user.login;
            process.env.INPUT_MODE = 'post-merge';

            // Execute the script
            eval(scriptContent);
