name: Pre-Merge Security Review

on:
  pull_request:
    types: [closed]

jobs:
  auto-security-review:
    # Only run if PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install @actions/core @actions/github

      - name: Check for security review approval
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Load configuration
            const configPath = path.join(process.env.GITHUB_WORKSPACE, '.github/security-review-config.json');
            const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
            console.log(`Using team: ${config.organization}/${config.team_slug}`);

            // Load the security review script
            const scriptPath = path.join(process.env.GITHUB_WORKSPACE, '.github/scripts/security-review.js');
            const scriptContent = fs.readFileSync(scriptPath, 'utf8');

            // Set up inputs for the script
            process.env.INPUT_GITHUB_TOKEN = process.env.GITHUB_TOKEN;
            process.env.INPUT_PR_NUMBER = context.payload.pull_request.number;
            process.env.INPUT_MODE = 'pre-merge';
            process.env.INPUT_ORG = config.organization;
            process.env['INPUT_TEAM-SLUG'] = config.team_slug;

            // Execute the script
            eval(scriptContent);
